// Adapter: Giulio's news drift signals (scrapers/news-feed/kyc_drift_signals.json)
// → our RawSignal[]. His signal_extractor.py already SELECTS + tags drift dimension;
// severity/scoring/recommendations are left to us (this pipeline) — exactly our split.
//
// His output: [{ company_id, legal_name, signals: [{ dimension, linked_entities,
//   title?, url?, published_at?, clean_text?/text?, source? }] }]
import { existsSync, readFileSync } from "node:fs";
import type { RawSignal, SignalCategory } from "../types.js";

// His 7 drift dimensions → our SignalCategory.
const DIMENSION_TO_CATEGORY: Record<string, SignalCategory> = {
  business_model_change: "business_model_pivot",
  activity_volume_change: "funding_scale_change",
  key_personnel_change: "ownership_change",
  ownership_change: "ownership_change",
  jurisdiction_structure_change: "jurisdiction_change",
  adverse_media_legal: "negative_news",
  sanctions_regulatory: "negative_news",
};

interface DriftSignal {
  dimension: string;
  linked_entities?: { name: string; role: string }[];
  title?: string;
  url?: string;
  published_at?: string;
  clean_text?: string;
  text?: string;
}
interface CompanyReport {
  company_id: string;
  legal_name: string;
  signals: DriftSignal[];
}

const DEFAULT_PATH = new URL("../../../scrapers/news-feed/kyc_drift_signals.json", import.meta.url);

/** Returns { clientId → RawSignal[] }. Empty if the file isn't generated yet. */
export function loadDriftSignals(path: URL | string = DEFAULT_PATH): Record<string, RawSignal[]> {
  if (!existsSync(path)) return {}; // generated by signal_extractor.py; absent until run
  const report = JSON.parse(readFileSync(path, "utf8")) as CompanyReport[];
  const out: Record<string, RawSignal[]> = {};

  for (const co of report) {
    const signals: RawSignal[] = [];
    co.signals.forEach((s, i) => {
      const category = DIMENSION_TO_CATEGORY[s.dimension];
      if (!category) return; // unknown dimension → skip
      const linked = (s.linked_entities ?? []).map((e) => `${e.name} (${e.role})`).join("; ");
      const body = s.clean_text ?? s.text ?? s.title ?? "";
      signals.push({
        signalId: `news-${co.company_id}-${i}`,
        clientId: co.company_id,
        category,
        detectedAt: s.published_at ?? "2026-06-20",
        sourceType: "news",
        sourceUrl: s.url,
        rawText: linked ? `${body}\n\nLinked entities (contagion): ${linked}` : body,
      });
    });
    out[co.company_id] = signals;
  }
  return out;
}
